from pathlib import Path

SYMBOLS = ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT", "BNB/USDT:USDT", "XRP/USDT:USDT"]
EXCHANGE_ID = "binanceusdm"
INITIAL_BALANCE = 20.0
RISK_PER_TRADE = 0.015
LEVERAGE = 10

TF_ENTRY = "15m"
TF_CONTEXT = "1h"
ATR_PERIOD = 14
RSI_PERIOD = 14
EMA_FAST = 20
EMA_SLOW = 50
PULLBACK_LOOKBACK = 6

ATR_MIN_PCT = 0.0008
ATR_MAX_PCT = 0.02
MOMENTUM_MIN_PCT = 0.0025
RSI_LONG_MIN = 52
RSI_SHORT_MAX = 48
MAX_PULLBACK_PCT = 0.0055
MIN_RECLAIM_BODY_PCT = 0.0010
SCORE_MIN_THRESHOLD = 0.62

SL_ATR_MULTIPLIER = 1.1
TP_ATR_MULTIPLIER = 2.4
SL_PCT_MAX = 0.006
TP_PCT_MAX = 0.012

MAX_HOLD_MINUTES = 12 * 60
BE_TRIGGER_PCT = 0.45
TRAILING_ACTIVATION_PCT = 0.85
TRAILING_DISTANCE_ATR = 0.55
FAST_FAIL_MINUTES = 60
MIN_PROGRESS_FOR_HOLD = 0.15
SCRATCH_EXIT_PCT = 0.0012

FEE_PCT = 0.0004
SLIPPAGE_PCT = 0.0001

DAILY_LOSS_LIMIT = 0.06
SESSION_DRAWDOWN_LIMIT = 0.04
CONSECUTIVE_LOSS_PAUSE = 3
MAX_TRADES_PER_DAY = 999999
PAUSE_MINUTES = 45

DATA_DIR = Path('intradia_selectivo_v1/data')
DB_PATH = DATA_DIR / 'trades.db'
LOG_PATH = DATA_DIR / 'bot.log'
BACKTEST_REPORT = Path('intradia_selectivo_v1_backtest_report.txt')
EQUITY_CURVE_CSV = Path('intradia_selectivo_v1_equity_curve.csv')

MAX_NOTIONAL_MULTIPLIER = 2.0
MAX_SYMBOL_NOTIONAL = {
    "BTC/USDT:USDT": 22.0,
    "ETH/USDT:USDT": 20.0,
    "SOL/USDT:USDT": 20.0,
    "BNB/USDT:USDT": 20.0,
    "XRP/USDT:USDT": 18.0,
}

SYMBOL_COOLDOWN_MINUTES = 90
SYMBOL_REPEAT_LOSS_COOLDOWN_MINUTES = 180

ALLOW_LONGS = True
ALLOW_SHORTS = True
REGIME_NEUTRAL_RSI_MIN = 46
REGIME_NEUTRAL_RSI_MAX = 54
