from pathlib import Path

SYMBOLS = ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT", "BNB/USDT:USDT", "XRP/USDT:USDT", "LINK/USDT:USDT"]
EXCHANGE_ID = "binanceusdm"
LEVERAGE = 10
RISK_PER_TRADE = 0.02
INITIAL_BALANCE = 20.0

TF_ENTRY = "5m"
TF_CONTEXT = "15m"
TF_EXECUTION = "1m"

ATR_PERIOD = 14
ATR_SL_MULTIPLIER = 1.5
ATR_TP_MULTIPLIER = 2.5
SL_PCT_MIN = 0.0025
SL_PCT_MAX = 0.0040
TP_RATIO = 1.8

MAX_HOLD_MINUTES = 60
BE_TRIGGER_PCT = 0.60
TRAILING_ACTIVATION_PCT = 0.75
TRAILING_DISTANCE_ATR = 0.5

MOMENTUM_LOOKBACK = 12
MOMENTUM_MIN_PCT = 0.0015
PULLBACK_MAX_DEPTH = 0.50
PULLBACK_MIN_CANDLES = 1
PULLBACK_MAX_CANDLES = 6
SCORE_MIN_THRESHOLD = 0.42

RSI_PERIOD = 14
RSI_LONG_MAX = 70
RSI_SHORT_MIN = 30
VOLUME_IMPULSE_RATIO = 1.15
VOLUME_PULLBACK_RATIO = 0.95
ATR_MIN_PCT = 0.0007
ATR_MAX_PCT = 0.015

FEE_PCT = 0.0004
SLIPPAGE_PCT = 0.0001

DAILY_LOSS_LIMIT = 0.06
SESSION_DRAWDOWN_LIMIT = 0.04
CONSECUTIVE_LOSS_PAUSE = 4
MAX_TRADES_PER_DAY = 15
PAUSE_MINUTES = 30

SESSIONS = [
    {"name": "Asia", "start": "01:00", "end": "04:00"},
    {"name": "London", "start": "07:00", "end": "11:00"},
    {"name": "NY", "start": "13:00", "end": "17:00"},
]

DATA_DIR = Path('momentum_pullback_v2/data')
DB_PATH = DATA_DIR / 'trades.db'
LOG_PATH = DATA_DIR / 'bot.log'
BACKTEST_REPORT = Path('momentum_pullback_v2_backtest_report.txt')
EQUITY_CURVE_CSV = Path('momentum_pullback_v2_equity_curve.csv')

STRATEGY_VARIANT = 'balanced'

MAX_NOTIONAL_MULTIPLIER = 2.5
MAX_SYMBOL_NOTIONAL = {
    "BTC/USDT:USDT": 35.0,
    "ETH/USDT:USDT": 30.0,
    "SOL/USDT:USDT": 25.0,
    "BNB/USDT:USDT": 25.0,
    "XRP/USDT:USDT": 20.0,
    "LINK/USDT:USDT": 20.0,
}
