from pathlib import Path

DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1493101893608804412/G75jhjvHaCXEXXvv6hOwnO2qScnUjFKNFDH5JgOPx6R8nWMOGVizceCRPtEC5AQJHIMU"
SYMBOLS = ["SOL/USDT:USDT"]

EXCHANGE_ID = "binanceusdm"
INITIAL_BALANCE = 100.0
RISK_PER_TRADE = 0.015
LEVERAGE = 10

TF_ENTRY = "5m"
TF_CONTEXT = "15m"
ATR_PERIOD = 14
RSI_PERIOD = 14
BB_PERIOD = 20
BB_STD = 2.0

RSI_LONG_MAX = 41
RSI_SHORT_MIN = 59
Z_SCORE_MIN = 0.48
ATR_MIN_PCT = 0.0006
ATR_MAX_PCT = 0.02
VWAP_STRETCH_MIN = 0.00045

SL_ATR_MULTIPLIER = 0.9
TP_ATR_MULTIPLIER = 2.20
SL_PCT_MAX = 0.0035
TP_PCT_MAX = 0.0032

MAX_HOLD_MINUTES = 20
BE_TRIGGER_PCT = 0.12
SECOND_BE_TRIGGER_PCT = 0.35
SECOND_BE_LOCK_ATR = 0.22
TRAILING_ACTIVATION_PCT = 0.27
TRAILING_DISTANCE_ATR = 0.27
GIVEBACK_PROGRESS_PCT = 0.45
GIVEBACK_RETRACE_PCT = 0.30
FAST_FAIL_MINUTES = 3
MIN_PROGRESS_FOR_HOLD = 0.20
SCRATCH_EXIT_PCT = 0.00025

SCORE_MIN_THRESHOLD = 0.48
SCORE_FILTER_MIN = 0.70
SCORE_FILTER_MAX = 0.75
ZSCORE_FILTER_MIN = 0.65
ZSCORE_FILTER_MAX = 0.80
FEE_PCT = 0.0004
SLIPPAGE_PCT = 0.0001
MIN_NET_EDGE_MULTIPLIER = 1.35

DAILY_LOSS_LIMIT = 0.05
SESSION_DRAWDOWN_LIMIT = 0.03
CONSECUTIVE_LOSS_PAUSE = 4
MAX_TRADES_PER_DAY = 999999
PAUSE_MINUTES = 12
MAX_CLOSED_TRADES_PER_RUN = 5

DATA_DIR = Path('reversion_scalp_v1_aggressive/data')
DB_PATH = DATA_DIR / 'trades.db'
LOG_PATH = DATA_DIR / 'bot.log'
NOTIFICATIONS_LOG_PATH = DATA_DIR / 'notifications.txt'
NOTIFICATIONS_CSV_PATH = DATA_DIR / 'notifications.csv'
BACKTEST_REPORT = Path('reversion_scalp_v1_aggressive_backtest_report.txt')
EQUITY_CURVE_CSV = Path('reversion_scalp_v1_aggressive_equity_curve.csv')

MAX_NOTIONAL_MULTIPLIER = 2.0
MAX_SYMBOL_NOTIONAL = {
    "SOL/USDT:USDT": 10.0,
}

MAX_CONCURRENT_TRADES = 1
MAX_CONCURRENT_TRADES_PER_SYMBOL = 1

SYMBOL_COOLDOWN_MINUTES = 20
SYMBOL_REPEAT_LOSS_COOLDOWN_MINUTES = 40

MANAGE_INTERVAL_S = 1   # frecuencia de monitoreo de posiciones abiertas
SCAN_INTERVAL_S = 20    # frecuencia de scan completo para buscar entradas
