from pathlib import Path

SYMBOLS = ["SOL/USDT:USDT", "XRP/USDT:USDT"]
EXCHANGE_ID = "binanceusdm"
INITIAL_BALANCE = 20.0
RISK_PER_TRADE = 0.015
LEVERAGE = 10

TF_ENTRY = "5m"
TF_CONTEXT = "15m"
ATR_PERIOD = 14
RSI_PERIOD = 14
BB_PERIOD = 20
BB_STD = 2.0

RSI_LONG_MAX = 39
RSI_SHORT_MIN = 61
Z_SCORE_MIN = 0.55
ATR_MIN_PCT = 0.0006
ATR_MAX_PCT = 0.02
VWAP_STRETCH_MIN = 0.00035

SL_ATR_MULTIPLIER = 0.82
TP_ATR_MULTIPLIER = 0.82
SL_PCT_MAX = 0.0032
TP_PCT_MAX = 0.0030

MAX_HOLD_MINUTES = 20
BE_TRIGGER_PCT = 0.10
TRAILING_ACTIVATION_PCT = 0.18
TRAILING_DISTANCE_ATR = 0.20
FAST_FAIL_MINUTES = 3
MIN_PROGRESS_FOR_HOLD = 0.12
SCRATCH_EXIT_PCT = 0.00045
MICRO_PARTIAL_TRIGGER_PCT = 0.32
MICRO_PARTIAL_SIZE = 0.45
MICRO_PARTIAL_LOCK_ATR = 0.08
MOMENTUM_DECAY_MINUTES = 5
MOMENTUM_DECAY_RETRACE = 0.20
GIVEBACK_EXIT_PROGRESS = 0.52
GIVEBACK_EXIT_RETRACE = 0.30

SCORE_MIN_THRESHOLD = 0.50
FEE_PCT = 0.0004
SLIPPAGE_PCT = 0.0001
MIN_NET_EDGE_MULTIPLIER = 1.10
MIN_REVERSAL_BODY_ATR = 0.16
MIN_RECLAIM_FRACTION = 0.22
SOL_SCORE_THRESHOLD = 0.54
XRP_SCORE_THRESHOLD = 0.49

DAILY_LOSS_LIMIT = 0.05
SESSION_DRAWDOWN_LIMIT = 0.03
CONSECUTIVE_LOSS_PAUSE = 4
MAX_TRADES_PER_DAY = 999999
PAUSE_MINUTES = 12

DATA_DIR = Path('reversion_scalp_v1/data')
DB_PATH = DATA_DIR / 'trades.db'
LOG_PATH = DATA_DIR / 'bot.log'
BACKTEST_REPORT = Path('reversion_scalp_v1_backtest_report.txt')
EQUITY_CURVE_CSV = Path('reversion_scalp_v1_equity_curve.csv')

MAX_NOTIONAL_MULTIPLIER = 2.0
MAX_SYMBOL_NOTIONAL = {
    "BTC/USDT:USDT": 20.0,
    "ETH/USDT:USDT": 18.0,
    "SOL/USDT:USDT": 20.0,
    "XRP/USDT:USDT": 16.0,
}

SYMBOL_COOLDOWN_MINUTES = 45
SYMBOL_REPEAT_LOSS_COOLDOWN_MINUTES = 90
