from pathlib import Path

SYMBOLS = ["BTC/USDT:USDT", "ETH/USDT:USDT", "SOL/USDT:USDT", "BNB/USDT:USDT", "XRP/USDT:USDT", "LINK/USDT:USDT"]
EXCHANGE_ID = "binanceusdm"
INITIAL_BALANCE = 20.0
RISK_PER_TRADE = 0.015
LEVERAGE = 10

TF_ENTRY = "5m"
TF_CONTEXT = "15m"
ATR_PERIOD = 14
RSI_PERIOD = 14
BB_PERIOD = 20
BB_STD = 2.0

RSI_LONG_MAX = 39
RSI_SHORT_MIN = 61
Z_SCORE_MIN = 0.55
ATR_MIN_PCT = 0.0006
ATR_MAX_PCT = 0.02
VWAP_STRETCH_MIN = 0.00035

SL_ATR_MULTIPLIER = 0.9
TP_ATR_MULTIPLIER = 0.8
SL_PCT_MAX = 0.0035
TP_PCT_MAX = 0.0030

MAX_HOLD_MINUTES = 20
BE_TRIGGER_PCT = 0.25
TRAILING_ACTIVATION_PCT = 0.45
TRAILING_DISTANCE_ATR = 0.35
FAST_FAIL_MINUTES = 8
MIN_PROGRESS_FOR_HOLD = 0.12
SCRATCH_EXIT_PCT = 0.0008

SCORE_MIN_THRESHOLD = 0.48
FEE_PCT = 0.0004
SLIPPAGE_PCT = 0.0001

DAILY_LOSS_LIMIT = 0.05
SESSION_DRAWDOWN_LIMIT = 0.03
CONSECUTIVE_LOSS_PAUSE = 3
MAX_TRADES_PER_DAY = 12
PAUSE_MINUTES = 30

DATA_DIR = Path('reversion_scalp_v1/data')
DB_PATH = DATA_DIR / 'trades.db'
LOG_PATH = DATA_DIR / 'bot.log'
BACKTEST_REPORT = Path('reversion_scalp_v1_backtest_report.txt')
EQUITY_CURVE_CSV = Path('reversion_scalp_v1_equity_curve.csv')

MAX_NOTIONAL_MULTIPLIER = 2.0
MAX_SYMBOL_NOTIONAL = {
    "BTC/USDT:USDT": 25.0,
    "ETH/USDT:USDT": 22.0,
    "SOL/USDT:USDT": 20.0,
    "BNB/USDT:USDT": 20.0,
    "XRP/USDT:USDT": 18.0,
    "LINK/USDT:USDT": 18.0,
}
