from flask import Flask, render_template_string
import os

app = Flask(__name__)

# Path to the summary report generated by your bot
REPORT_PATH = '/home/lucapicone/luca123/reversion_scalp_v1/summary_report.txt'

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Trading Bot Dashboard</title>
    <style>
        body { font-family: sans-serif; padding: 20px; background: #121212; color: #eee; }
        pre { background: #222; padding: 15px; border-radius: 5px; overflow-x: auto; }
        h1 { color: #00ff00; }
    </style>
</head>
<body>
    <h1>Bot Scalper Dashboard</h1>
    <p>Last Update: {{ last_update }}</p>
    <pre>{{ report_content }}</pre>
</body>
</html>
"""

@app.route('/')
def index():
    if os.path.exists(REPORT_PATH):
        with open(REPORT_PATH, 'r') as f:
            content = f.read()
        import datetime
        mtime = os.path.getmtime(REPORT_PATH)
        last_update = datetime.datetime.fromtimestamp(mtime).strftime('%Y-%m-%d %H:%M:%S')
    else:
        content = "Summary report not found yet."
        last_update = "N/A"
    return render_template_string(HTML_TEMPLATE, report_content=content, last_update=last_update)

if __name__ == '__main__':
    app.run()
